core.entity_form_display.*.*.*.third_party.display_machine_name:
  type: mapping
  label: 'Display machine name settings'
  mapping:
    enable_display_machine_name:
      type: integer
      label: 'Enable display machine name'

